Repository ezcode-my/backend, pull requests merged in 2025-07, with the labels that each got.

#123 fix: input이 null일 때 방어코드 추가
  src/main/java/org/ezcode/codetest/common/security/config/SecurityConfig.java
  src/main/java/org/ezcode/codetest/domain/problem/model/entity/Testcase.java
  src/main/resources/templates/submit-test.html
Labels: bug

#128 refactor : 알림 데이터 추가 및 관련 문서 작성
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyVoteService.java
  src/main/java/org/ezcode/codetest/application/notification/enums/NotificationType.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/DiscussionVotePayload.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/ReplyCreatePayload.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/ReplyVotePayload.java
  src/main/java/org/ezcode/codetest/domain/community/model/entity/Reply.java
  src/main/java/org/ezcode/codetest/domain/community/service/DiscussionVoteDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/ReplyDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/ReplyVoteDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/notification/dto/NotificationResponse.java
  src/main/java/org/ezcode/codetest/presentation/notification/NotificationController.java
Labels: documentation, enhancement

#132 refactor: 깃 푸시 경로 수정 및 커밋 메세지 수정
  src/main/java/org/ezcode/codetest/application/submission/dto/request/github/GitHubPushRequest.java
  src/main/java/org/ezcode/codetest/infrastructure/github/GitHubApiClient.java
  src/main/java/org/ezcode/codetest/infrastructure/github/GitHubContentBuilder.java
Labels: enhancement

#134 fix: 타이밍 문제로 init 받아지지 않는 문제 해결
  src/main/java/org/ezcode/codetest/application/submission/service/SubmissionService.java
  src/main/java/org/ezcode/codetest/infrastructure/event/listener/RedisJudgeQueueConsumer.java
  src/main/java/org/ezcode/codetest/infrastructure/event/publisher/StompMessageService.java
Labels: bug

#133 test : 문제 테스트 코드 작성
  src/test/java/org/ezcode/codetest/application/problem/service/ProblemServiceTest.java
  src/test/java/org/ezcode/codetest/domain/problem/service/ProblemDomainServiceTest.java
Labels: Test

#135 refactor : 총 제출 횟수, 성공한 제출 횟수 dto추가
  src/main/java/org/ezcode/codetest/application/problem/dto/response/ProblemResponse.java
Labels: documentation

#138 refactor : BooleanBuilder 조합 위치 변경
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemQueryRepositoryImpl.java
Labels: documentation

#156 refactor : 문제 이미지만 수정 로직, UI 부분 추가
  src/main/java/org/ezcode/codetest/application/problem/dto/response/ProblemDetailResponse.java
  src/main/java/org/ezcode/codetest/application/problem/service/ProblemService.java
  src/main/java/org/ezcode/codetest/presentation/problemmanagement/problem/ProblemAdminController.java
  src/main/resources/templates/test-submit.html
Labels: documentation

#158 fix : 문제 이미지 누락된 코드 수정
  src/main/resources/templates/test-submit.html
Labels: bug, enhancement

#160 feat : 토론글 목록 조회 시 languageId 필드 추가 및 프론트 적용
  src/main/java/org/ezcode/codetest/application/community/dto/response/DiscussionResponse.java
  src/main/java/org/ezcode/codetest/domain/community/dto/DiscussionQueryResult.java
  src/main/java/org/ezcode/codetest/domain/community/model/entity/Discussion.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/discussion/DiscussionQueryRepositoryImpl.java
  src/main/resources/templates/test-submit.html
Labels: enhancement

#162 chore : 웹소켓 핫빗 주기 변경
  src/main/java/org/ezcode/codetest/infrastructure/event/config/WebSocketConfig.java
Labels: enhancement

#167 fix: cors error in swagger
  src/main/java/org/ezcode/codetest/infrastructure/swagger/config/SwaggerConfig.java
Labels: bug

#170 refactor: 제출 로직 리팩토링
  src/main/java/org/ezcode/codetest/application/problem/service/ProblemService.java
  src/main/java/org/ezcode/codetest/application/submission/dto/event/ProblemCountAdjustmentEvent.java
  src/main/java/org/ezcode/codetest/application/submission/model/SubmissionContext.java
  src/main/java/org/ezcode/codetest/application/submission/port/SubmissionEventService.java
  src/main/java/org/ezcode/codetest/application/submission/service/JudgementService.java
  src/main/java/org/ezcode/codetest/application/submission/service/SubmissionService.java
  src/main/java/org/ezcode/codetest/common/config/ExecutorConfig.java
  src/main/java/org/ezcode/codetest/domain/problem/repository/ProblemRepository.java
  src/main/java/org/ezcode/codetest/domain/problem/service/ProblemDomainService.java
  src/main/java/org/ezcode/codetest/domain/submission/model/SubmissionResult.java
  src/main/java/org/ezcode/codetest/domain/submission/service/SubmissionDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/event/config/RedisStreamConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/event/config/RedisStreamConsumerRegistrar.java
  src/main/java/org/ezcode/codetest/infrastructure/event/listener/SubmissionEventListener.java
  src/main/java/org/ezcode/codetest/infrastructure/event/publisher/SubmissionEventPublisher.java
  src/main/java/org/ezcode/codetest/infrastructure/event/scheduler/RedisStreamMonitor.java
  src/main/java/org/ezcode/codetest/infrastructure/judge0/Judge0Client.java
  src/main/java/org/ezcode/codetest/infrastructure/lock/RedisLockManager.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/submission/query/SubmissionQueryRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/redis/CommonRedisConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/scheduler/WeeklyTokenResetScheduler.java
  src/main/resources/application.properties
  src/test/java/org/ezcode/codetest/domain/submission/SubmissionDomainServiceTest.java
  src/test/java/org/ezcode/codetest/infrastructure/judge0/Judge0ClientTest.java
Labels: bug, enhancement
