Repository ezcode-my/backend, pull requests merged in 2025-06, with the labels that each got.

#14 feat : 자유글(discussion) CRUD 구현
  .gitignore
  src/main/java/org/ezcode/codetest/application/community/.gitkeep
  src/main/java/org/ezcode/codetest/application/community/dto/.gitkeep
  src/main/java/org/ezcode/codetest/application/community/dto/request/DiscussionCreateRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/request/DiscussionModifyRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/DiscussionResponse.java
  src/main/java/org/ezcode/codetest/application/community/port/.gitkeep
  src/main/java/org/ezcode/codetest/application/community/service/.gitkeep
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionService.java
  src/main/java/org/ezcode/codetest/application/usermanagement/user/dto/SimpleUserInfoResponse.java
  src/main/java/org/ezcode/codetest/application/usermanagement/user/dto/UserInfoResponse.java
  src/main/java/org/ezcode/codetest/domain/community/exception/.gitkeep
  src/main/java/org/ezcode/codetest/domain/community/exception/CommunityException.java
  src/main/java/org/ezcode/codetest/domain/community/exception/CommunityExceptionCode.java
  src/main/java/org/ezcode/codetest/domain/community/model/Discussion.java
  src/main/java/org/ezcode/codetest/domain/community/repository/DiscussionRepository.java
  src/main/java/org/ezcode/codetest/domain/community/service/.gitkeep
  src/main/java/org/ezcode/codetest/domain/community/service/DiscussionDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/ReplyDomainService.java
  src/main/java/org/ezcode/codetest/domain/problem/service/LanguageDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/DiscussionJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/DiscussionRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/PostController.java
  src/main/java/org/ezcode/codetest/presentation/community/DiscussionController.java
Labels: enhancement

#22 refactor : User 로그인, 로그아웃을 redis로 구현, AuthUser 리팩토링
  src/main/java/org/ezcode/codetest/application/usermanagement/auth/port/JwtUtil.java
  src/main/java/org/ezcode/codetest/application/usermanagement/auth/service/AuthService.java
  src/main/java/org/ezcode/codetest/application/usermanagement/user/dto/LogoutResponse.java
  src/main/java/org/ezcode/codetest/domain/user/exception/AuthExceptionCode.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/AuthUser.java
  src/main/java/org/ezcode/codetest/infrastructure/security/config/FilterConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/security/config/SecurityConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/security/jwt/ExceptionHandlingFilter.java
  src/main/java/org/ezcode/codetest/infrastructure/security/jwt/JwtFilter.java
  src/main/java/org/ezcode/codetest/infrastructure/security/jwt/JwtUtilImpl.java
  src/main/java/org/ezcode/codetest/presentation/usermanagement/AuthController.java
  src/main/java/org/ezcode/codetest/presentation/usermanagement/UserController.java
Labels: enhancement

#28 feat : 1차 캐시 사용하도록 코드 최적화
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyVoteService.java
  src/main/java/org/ezcode/codetest/domain/community/model/BaseVote.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/discussion/DiscussionJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/discussion/DiscussionRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/reply/ReplyJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/reply/ReplyRepositoryImpl.java
Labels: enhancement

#30 feat / refactor : 제출 기록 및 제출 히스토리 기능 구현
  .gitignore
  src/main/java/org/ezcode/codetest/application/submission/dto/response/SubmissionHistoryResponse.java
  src/main/java/org/ezcode/codetest/application/submission/dto/response/SubmitResponse.java
  src/main/java/org/ezcode/codetest/application/submission/model/JudgeResult.java
  src/main/java/org/ezcode/codetest/application/submission/service/SubmissionService.java
  src/main/java/org/ezcode/codetest/common/model/TempProblemInfo.java
  src/main/java/org/ezcode/codetest/domain/problem/exception/SubmissionException.java
  src/main/java/org/ezcode/codetest/domain/problem/exception/code/SubmissionExceptionCode.java
  src/main/java/org/ezcode/codetest/domain/problem/model/dto/AnswerEvaluation.java
  src/main/java/org/ezcode/codetest/domain/problem/model/dto/SubmissionData.java
  src/main/java/org/ezcode/codetest/domain/problem/model/dto/SubmitProcessResult.java
  src/main/java/org/ezcode/codetest/domain/problem/model/entity/Submission.java
  src/main/java/org/ezcode/codetest/domain/problem/model/entity/UserProblemResult.java
  src/main/java/org/ezcode/codetest/domain/problem/model/enums/SubmitStatus.java
  src/main/java/org/ezcode/codetest/domain/problem/repository/SubmissionRepository.java
  src/main/java/org/ezcode/codetest/domain/problem/repository/UserProblemResultRepository.java
  src/main/java/org/ezcode/codetest/domain/problem/service/SubmissionDomainService.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/RankPoint.java
  src/main/java/org/ezcode/codetest/infrastructure/judge0/Judge0ResponseMapper.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/SubmissionJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/SubmissionRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/UserProblemResultJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/UserProblemResultRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/UserProblemStatusJpaRepository.java
  src/main/java/org/ezcode/codetest/presentation/SubmissionController.java
  src/main/resources/application.properties
Labels: enhancement

#39 feat : 알림 기능 구현
  src/main/java/org/ezcode/codetest/application/community/service/BaseVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyVoteService.java
  src/main/java/org/ezcode/codetest/application/notification/.gitkeep
  src/main/java/org/ezcode/codetest/application/notification/dto/.gitkeep
  src/main/java/org/ezcode/codetest/application/notification/dto/NotificationCreateEvent.java
  src/main/java/org/ezcode/codetest/application/notification/dto/NotificationListRequestEvent.java
  src/main/java/org/ezcode/codetest/application/notification/dto/NotificationReadEvent.java
  src/main/java/org/ezcode/codetest/application/notification/enums/NotificationType.java
  src/main/java/org/ezcode/codetest/application/notification/port/.gitkeep
  src/main/java/org/ezcode/codetest/application/notification/port/NotificationEventDtoFactory.java
  src/main/java/org/ezcode/codetest/application/notification/port/NotificationEventService.java
  src/main/java/org/ezcode/codetest/application/notification/service/.gitkeep
  src/main/java/org/ezcode/codetest/application/notification/service/NotificationUseCase.java
  src/main/java/org/ezcode/codetest/domain/notification/exception/.gitkeep
  src/main/java/org/ezcode/codetest/domain/notification/model/Notification.java
  src/main/java/org/ezcode/codetest/domain/notification/model/NotificationType.java
  src/main/java/org/ezcode/codetest/domain/notification/service/.gitkeep
  src/main/java/org/ezcode/codetest/domain/user/model/entity/User.java
  src/main/java/org/ezcode/codetest/infrastructure/cache/config/CacheRedisConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/event/dto/NotificationRecord.java
  src/main/java/org/ezcode/codetest/infrastructure/event/dto/NotificationResponse.java
  src/main/java/org/ezcode/codetest/infrastructure/event/listener/NotificationEventListener.java
  src/main/java/org/ezcode/codetest/infrastructure/event/service/NotificationEventPublisher.java
  src/main/java/org/ezcode/codetest/infrastructure/event/service/StompMessageService.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/notification/NotificationJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/notification/NotificationRedisRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/notification/NotificationRepository.java
  src/main/java/org/ezcode/codetest/presentation/notification/NotificationController.java
  src/main/resources/templates/chat-page.html
Labels: enhancement

#45 refactor : 이벤트 객체 생성 부분 리팩토링
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyVoteService.java
  src/main/java/org/ezcode/codetest/application/notification/dto/event/DiscussionVoteEvent.java
  src/main/java/org/ezcode/codetest/application/notification/dto/event/ReplyCreateEvent.java
  src/main/java/org/ezcode/codetest/application/notification/dto/event/ReplyVoteEvent.java
  src/main/java/org/ezcode/codetest/application/notification/event/NotificationCreateEvent.java
  src/main/java/org/ezcode/codetest/application/notification/event/NotificationListRequestEvent.java
  src/main/java/org/ezcode/codetest/application/notification/event/NotificationReadEvent.java
  src/main/java/org/ezcode/codetest/application/notification/event/converter/NotificationConverter.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/DiscussionVoteNotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/NotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/ReplyCreateNotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/ReplyVoteNotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/DiscussionVotePayload.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/NotificationPayload.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/ReplyCreatePayload.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/ReplyVotePayload.java
  src/main/java/org/ezcode/codetest/application/notification/exception/NotificationException.java
  src/main/java/org/ezcode/codetest/application/notification/exception/NotificationExceptionCode.java
  src/main/java/org/ezcode/codetest/application/notification/port/NotificationEventDtoFactory.java
  src/main/java/org/ezcode/codetest/application/notification/port/NotificationEventService.java
  src/main/java/org/ezcode/codetest/application/notification/service/NotificationUseCase.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/User.java
  src/main/java/org/ezcode/codetest/infrastructure/event/dto/NotificationRecord.java
  src/main/java/org/ezcode/codetest/infrastructure/event/dto/NotificationResponse.java
  src/main/java/org/ezcode/codetest/infrastructure/event/listener/NotificationEventListener.java
  src/main/java/org/ezcode/codetest/infrastructure/event/service/NotificationEventPublisher.java
Labels: enhancement

#47 hotfix : 검색엔진 버그 수정
  src/main/resources/elasticsearch/my_index-settings.json
Labels: bug

#51 docs : Swagger 문서화를 위한 컨트롤러 및 DTO 어노테이션 추가
  src/main/java/org/ezcode/codetest/application/submission/dto/request/language/LanguageCreateRequest.java
  src/main/java/org/ezcode/codetest/application/submission/dto/request/language/LanguageUpdateRequest.java
  src/main/java/org/ezcode/codetest/application/submission/dto/request/review/CodeReviewRequest.java
  src/main/java/org/ezcode/codetest/application/submission/dto/request/submission/CodeSubmitRequest.java
  src/main/java/org/ezcode/codetest/application/submission/dto/response/language/LanguageResponse.java
  src/main/java/org/ezcode/codetest/application/submission/dto/response/review/CodeReviewResponse.java
  src/main/java/org/ezcode/codetest/application/submission/dto/response/submission/FinalResultResponse.java
  src/main/java/org/ezcode/codetest/application/submission/dto/response/submission/GroupedSubmissionResponse.java
  src/main/java/org/ezcode/codetest/application/submission/dto/response/submission/JudgeResultResponse.java
  src/main/java/org/ezcode/codetest/application/submission/dto/response/submission/SubmissionDetailResponse.java
  src/main/java/org/ezcode/codetest/presentation/language/LanguageController.java
  src/main/java/org/ezcode/codetest/presentation/submission/SubmissionController.java
Labels: documentation

#52 docs : Swagger 어노테이션 추가 - 커뮤니티 및 알림 controller/dto
  src/main/java/org/ezcode/codetest/application/community/dto/request/DiscussionCreateRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/request/DiscussionModifyRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/request/ReplyCreateRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/request/ReplyModifyRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/DiscussionResponse.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/ReplyResponse.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/VoteResponse.java
  src/main/java/org/ezcode/codetest/presentation/community/DiscussionController.java
  src/main/java/org/ezcode/codetest/presentation/community/DiscussionVoteController.java
  src/main/java/org/ezcode/codetest/presentation/community/ReplyController.java
  src/main/java/org/ezcode/codetest/presentation/community/ReplyVoteController.java
  src/main/java/org/ezcode/codetest/presentation/notification/NotificationController.java
Labels: documentation

#53 feature: Swagger 문서화 및 중복 문제 검증로직 추가
  src/main/java/org/ezcode/codetest/application/problem/dto/request/ProblemCreateRequest.java
  src/main/java/org/ezcode/codetest/application/problem/dto/request/ProblemUpdateRequest.java
  src/main/java/org/ezcode/codetest/application/problem/dto/request/TestcaseCreateRequest.java
  src/main/java/org/ezcode/codetest/application/problem/dto/request/TestcaseUpdateRequest.java
  src/main/java/org/ezcode/codetest/application/problem/dto/response/ProblemDetailResponse.java
  src/main/java/org/ezcode/codetest/application/problem/dto/response/ProblemResponse.java
  src/main/java/org/ezcode/codetest/application/problem/dto/response/TestcaseResponse.java
  src/main/java/org/ezcode/codetest/domain/problem/exception/code/ProblemExceptionCode.java
  src/main/java/org/ezcode/codetest/domain/problem/repository/ProblemRepository.java
  src/main/java/org/ezcode/codetest/domain/problem/service/ProblemDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/problemmanagement/problem/ProblemAdminController.java
  src/main/java/org/ezcode/codetest/presentation/problemmanagement/problem/ProblemController.java
  src/main/java/org/ezcode/codetest/presentation/problemmanagement/testcase/TestcaseAdminController.java
Labels: documentation, enhancement

#63 feature : 동적 쿼리 적용, /api 경로 추가
  build.gradle
  src/main/java/org/ezcode/codetest/application/problem/service/ProblemService.java
  src/main/java/org/ezcode/codetest/domain/problem/model/ProblemSearchCondition.java
  src/main/java/org/ezcode/codetest/domain/problem/repository/ProblemRepository.java
  src/main/java/org/ezcode/codetest/domain/problem/service/ProblemDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/config/.gitkeep
  src/main/java/org/ezcode/codetest/infrastructure/persistence/config/QuerydslConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemQueryRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemRepositoryCustom.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/problemmanagement/problem/ProblemAdminController.java
  src/main/java/org/ezcode/codetest/presentation/problemmanagement/problem/ProblemController.java
  src/main/java/org/ezcode/codetest/presentation/problemmanagement/testcase/TestcaseAdminController.java
Labels: enhancement

#65 refactor : 커뮤니티 및 알림 코드 리팩토링
  src/main/java/org/ezcode/codetest/application/community/dto/request/ReplyCreateRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/VoteResponse.java
  src/main/java/org/ezcode/codetest/application/community/service/BaseVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionService.java
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyVoteService.java
  src/main/java/org/ezcode/codetest/application/notification/dto/event/DiscussionVoteEvent.java
  src/main/java/org/ezcode/codetest/application/notification/dto/event/ReplyCreateEvent.java
  src/main/java/org/ezcode/codetest/application/notification/dto/event/ReplyVoteEvent.java
  src/main/java/org/ezcode/codetest/application/notification/enums/NotificationType.java
  src/main/java/org/ezcode/codetest/application/notification/event/NotificationCreateEvent.java
  src/main/java/org/ezcode/codetest/application/notification/event/converter/NotificationConverter.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/DiscussionVoteNotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/NotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/ReplyCreateNotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/mapper/ReplyVoteNotificationMapper.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/DiscussionVotePayload.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/ReplyCreatePayload.java
  src/main/java/org/ezcode/codetest/application/notification/event/payload/ReplyVotePayload.java
  src/main/java/org/ezcode/codetest/domain/community/model/Discussion.java
  src/main/java/org/ezcode/codetest/domain/community/model/Reply.java
  src/main/java/org/ezcode/codetest/domain/community/service/BaseVoteDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/DiscussionDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/DiscussionVoteDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/ReplyDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/ReplyVoteDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/event/dto/NotificationRecord.java
  src/main/java/org/ezcode/codetest/presentation/community/DiscussionController.java
  src/main/java/org/ezcode/codetest/presentation/community/DiscussionVoteController.java
  src/main/java/org/ezcode/codetest/presentation/community/ReplyController.java
  src/main/java/org/ezcode/codetest/presentation/community/ReplyVoteController.java
  src/main/java/org/ezcode/codetest/presentation/notification/NotificationController.java
Labels: enhancement

#69 feat : 추천/추천 취소 기능 -> 추천/비추천 기능으로 변경 + 테스트 코드 작성
  src/main/java/org/ezcode/codetest/application/community/dto/request/DiscussionCreateRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/request/ReplyCreateRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/request/VoteRequest.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/DiscussionResponse.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/ReplyResponse.java
  src/main/java/org/ezcode/codetest/application/community/dto/response/VoteResponse.java
  src/main/java/org/ezcode/codetest/application/community/service/BaseVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionService.java
  src/main/java/org/ezcode/codetest/application/community/service/DiscussionVoteService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyService.java
  src/main/java/org/ezcode/codetest/application/community/service/ReplyVoteService.java
  src/main/java/org/ezcode/codetest/domain/community/model/VoteResult.java
  src/main/java/org/ezcode/codetest/domain/community/model/entity/BaseVote.java
  src/main/java/org/ezcode/codetest/domain/community/model/entity/Discussion.java
  src/main/java/org/ezcode/codetest/domain/community/model/entity/DiscussionVote.java
  src/main/java/org/ezcode/codetest/domain/community/model/entity/Reply.java
  src/main/java/org/ezcode/codetest/domain/community/model/entity/ReplyVote.java
  src/main/java/org/ezcode/codetest/domain/community/model/enums/VoteType.java
  src/main/java/org/ezcode/codetest/domain/community/repository/BaseVoteRepository.java
  src/main/java/org/ezcode/codetest/domain/community/repository/DiscussionRepository.java
  src/main/java/org/ezcode/codetest/domain/community/repository/DiscussionVoteRepository.java
  src/main/java/org/ezcode/codetest/domain/community/repository/ReplyRepository.java
  src/main/java/org/ezcode/codetest/domain/community/repository/ReplyVoteRepository.java
  src/main/java/org/ezcode/codetest/domain/community/service/BaseVoteDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/DiscussionDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/DiscussionVoteDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/ReplyDomainService.java
  src/main/java/org/ezcode/codetest/domain/community/service/ReplyVoteDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/discussion/DiscussionJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/discussion/DiscussionRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/reply/ReplyJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/reply/ReplyRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/vote/DiscussionVoteJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/vote/DiscussionVoteRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/vote/ReplyVoteJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/community/vote/ReplyVoteRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/LikeController.java
  src/main/java/org/ezcode/codetest/presentation/community/DiscussionVoteController.java
  src/main/java/org/ezcode/codetest/presentation/community/ReplyVoteController.java
  src/test/java/org/ezcode/codetest/domain/community/service/DiscussionVoteDomainServiceTest.java
  src/test/java/org/ezcode/codetest/domain/community/service/ReplyVoteDomainServiceTest.java
  src/test/java/org/ezcode/codetest/support/fixture/CommunityFixture.java
Labels: documentation, enhancement

#72 Refactor : user테이블 AuthType 분리
  src/main/java/org/ezcode/codetest/application/usermanagement/auth/service/AuthService.java
  src/main/java/org/ezcode/codetest/application/usermanagement/user/service/UserService.java
  src/main/java/org/ezcode/codetest/common/security/config/SecurityConfig.java
  src/main/java/org/ezcode/codetest/common/security/hander/CustomSuccessHandler.java
  src/main/java/org/ezcode/codetest/common/security/util/JwtFilter.java
  src/main/java/org/ezcode/codetest/common/security/util/SecurityPath.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/User.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/UserAuthType.java
  src/main/java/org/ezcode/codetest/domain/user/repository/UserAuthTypeRepository.java
  src/main/java/org/ezcode/codetest/domain/user/repository/UserRepository.java
  src/main/java/org/ezcode/codetest/domain/user/service/CustomOAuth2UserService.java
  src/main/java/org/ezcode/codetest/domain/user/service/UserDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/user/UserAuthTypeJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/user/UserAuthTypeRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/user/UserJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/user/UserRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/usermanagement/AuthController.java
  src/main/resources/application.properties
Labels: enhancement

#71 feat : 메인 or 랭킹화면 랭킹 구현(지난주,이번주,역대 TOP10)
  src/main/java/org/ezcode/codetest/application/ranking/dto/RankingResponse.java
  src/main/java/org/ezcode/codetest/application/ranking/service/RankingFacadeService.java
  src/main/java/org/ezcode/codetest/domain/ranking/model/entity/Ranking.java
  src/main/java/org/ezcode/codetest/domain/ranking/model/enums/RankingType.java
  src/main/java/org/ezcode/codetest/domain/ranking/repository/RankingRepository.java
  src/main/java/org/ezcode/codetest/domain/submission/repository/UserProblemResultRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/submission/impl/UserProblemResultRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/submission/jpa/UserProblemResultJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/user/UserJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/ranking/redis/RedisRankingService.java
  src/main/java/org/ezcode/codetest/infrastructure/ranking/scheduler/RankingSyncScheduler.java
  src/main/java/org/ezcode/codetest/presentation/ranking/RankingController.java
Labels: enhancement

#73 refactor : AI 코드리뷰 프롬프트 정형화 v2
  src/main/java/org/ezcode/codetest/application/submission/model/OpenAIResponse.java
  src/main/java/org/ezcode/codetest/domain/submission/exception/CodeReviewException.java
  src/main/java/org/ezcode/codetest/domain/submission/exception/code/CodeReviewExceptionCode.java
  src/main/java/org/ezcode/codetest/infrastructure/openai/OpenAIMessageBuilder.java
  src/main/java/org/ezcode/codetest/infrastructure/openai/OpenAIResponseValidator.java
  src/main/java/org/ezcode/codetest/infrastructure/openai/OpenAIReviewClient.java
  src/main/java/org/ezcode/codetest/infrastructure/openai/OpenAiClient.java
  src/main/resources/templates/submit-test.html
Labels: enhancement

#85 feat : 랜덤 인카운터 추가, jwt 를 이용한 일시적인 이벤트 생성, 하루에 인카운터, 배틀 횟수 제한 토큰 생성
  src/main/java/org/ezcode/codetest/application/game/dto/request/encounter/BattleRequest.java
  src/main/java/org/ezcode/codetest/application/game/dto/request/encounter/EncounterChoiceRequest.java
  src/main/java/org/ezcode/codetest/application/game/dto/request/encounter/RandomEncounterSaveRequest.java
  src/main/java/org/ezcode/codetest/application/game/dto/response/encounter/EncounterResponse.java
  src/main/java/org/ezcode/codetest/application/game/dto/response/encounter/MatchingBattleResponse.java
  src/main/java/org/ezcode/codetest/application/game/dto/response/encounter/MatchingEncounterResponse.java
  src/main/java/org/ezcode/codetest/application/game/play/GamePlayUseCase.java
  src/main/java/org/ezcode/codetest/application/usermanagement/auth/service/AuthService.java
  src/main/java/org/ezcode/codetest/common/security/hander/CustomSuccessHandler.java
  src/main/java/org/ezcode/codetest/common/security/util/JwtUtil.java
  src/main/java/org/ezcode/codetest/domain/game/exception/GameExceptionCode.java
  src/main/java/org/ezcode/codetest/domain/game/model/character/GameCharacter.java
  src/main/java/org/ezcode/codetest/domain/game/model/character/GameCharacterMatchTokenBucket.java
  src/main/java/org/ezcode/codetest/domain/game/model/encounter/EncounterLog.java
  src/main/java/org/ezcode/codetest/domain/game/model/encounter/RandomEncounter.java
  src/main/java/org/ezcode/codetest/domain/game/repository/MatchTokenBucketRepository.java
  src/main/java/org/ezcode/codetest/domain/game/service/CharacterStatusDomainService.java
  src/main/java/org/ezcode/codetest/domain/game/service/GameEncounterDomainService.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/AmbushBanditsBad.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/AmbushBanditsGood.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/AncientRuinsTrap.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/BossEncounterBad.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/GamblingBad.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/StatSpeed.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/TreasureCacheFound.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/WildBeastsAttack.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/WildBeastsEscape.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/skill/skilldecorator/DefencePenetrationDecorator.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/skill/skillstrategyimpl/ButterflySkill.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/skill/skillstrategyimpl/DefencePenetrationSkill.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/skill/skillstrategyimpl/NoSkill.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/game/mysql/character/MatchTokenBucketJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/game/mysql/character/MatchTokenBucketRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/game/play/GamePlayController.java
Labels: enhancement

#88 feat : 게임 ui 생성 완료
  src/main/java/org/ezcode/codetest/application/game/dto/response/encounter/EncounterResponse.java
  src/main/java/org/ezcode/codetest/application/game/dto/response/encounter/MatchingEncounterResponse.java
  src/main/java/org/ezcode/codetest/common/security/util/JwtUtil.java
  src/main/java/org/ezcode/codetest/common/security/util/SecurityPath.java
  src/main/java/org/ezcode/codetest/domain/game/model/character/CharacterRealStat.java
  src/main/java/org/ezcode/codetest/domain/game/service/CharacterStatusDomainService.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/encounter/encounterstrategyimpl/AmbushBanditsGood.java
  src/main/java/org/ezcode/codetest/presentation/game/play/GamePlayController.java
  src/main/java/org/ezcode/codetest/presentation/game/play/TestGamePlayController.java
  src/main/java/org/ezcode/codetest/presentation/game/view/GameViewController.java
  src/main/resources/static/images/15328_green_noisy_nobg.gif
  src/main/resources/static/images/vault_boy_transparent.gif
  src/main/resources/static/images/vaultboy_green_filtered.gif
  src/main/resources/templates/game-page.html
Labels: enhancement, Test

#87 feat : 신고 기능 개발
  src/main/java/org/ezcode/codetest/application/report/dto/ReportChangeResponse.java
  src/main/java/org/ezcode/codetest/application/report/dto/ReportDetailResponse.java
  src/main/java/org/ezcode/codetest/application/report/dto/ReportListResponse.java
  src/main/java/org/ezcode/codetest/application/report/dto/ReportRequest.java
  src/main/java/org/ezcode/codetest/application/report/dto/ReportResponse.java
  src/main/java/org/ezcode/codetest/application/report/dto/ReportStatusUpdateRequest.java
  src/main/java/org/ezcode/codetest/application/report/port/ReportRepository.java
  src/main/java/org/ezcode/codetest/application/report/service/ReportService.java
  src/main/java/org/ezcode/codetest/domain/report/model/Report.java
  src/main/java/org/ezcode/codetest/domain/report/model/ReportStatus.java
  src/main/java/org/ezcode/codetest/domain/report/model/ReportTargetType.java
  src/main/java/org/ezcode/codetest/domain/report/model/ReportType.java
  src/main/java/org/ezcode/codetest/domain/report/repository/ReportRepository.java
  src/main/java/org/ezcode/codetest/domain/report/service/ReportDomainService.java
  src/main/java/org/ezcode/codetest/presentation/ReportController.java
  src/main/java/org/ezcode/codetest/presentation/report/ReportAdminController.java
  src/main/java/org/ezcode/codetest/presentation/report/ReportController.java
  src/main/resources/application.properties
Labels: enhancement

#90 feat : 방어 전투 로그 조회할 수 있는 기능 추가, 성능 개선
  src/main/java/org/ezcode/codetest/application/game/dto/response/encounter/DefenceBattleHistoryResponse.java
  src/main/java/org/ezcode/codetest/application/game/play/GamePlayUseCase.java
  src/main/java/org/ezcode/codetest/domain/game/model/character/CharacterRealStat.java
  src/main/java/org/ezcode/codetest/domain/game/repository/BattleHistoryRepository.java
  src/main/java/org/ezcode/codetest/domain/game/service/GameEncounterDomainService.java
  src/main/java/org/ezcode/codetest/domain/game/strategy/skill/skillstrategyimpl/LifeStealSkill.java
  src/main/java/org/ezcode/codetest/domain/game/util/StatUpdateUtil.java
  src/main/java/org/ezcode/codetest/infrastructure/cache/config/CaffeineCacheConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/event/config/CustomHandShakeHandler.java
  src/main/java/org/ezcode/codetest/infrastructure/event/listener/WebSocketEventListener.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/game/mysql/character/GameCharacterRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/game/mysql/encounter/BattleHistoryJpaRepository.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/game/mysql/encounter/BattleHistoryRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/game/mysql/encounter/EncounterChoiceRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/game/play/GamePlayController.java
  src/main/resources/templates/game-page.html
Labels: enhancement

#102 refactor : 트랜잭션 범위 내 외부 서비스 호출 처리
  src/main/java/org/ezcode/codetest/application/problem/service/ProblemService.java
Labels: documentation

#105 Feature : Github OAuth 구현, OAuth 통합 컨트롤러, AES 암호화, Github access token 저장
  build.gradle
  src/main/java/org/ezcode/codetest/application/usermanagement/user/dto/response/GithubOAuth2Response.java
  src/main/java/org/ezcode/codetest/application/usermanagement/user/dto/response/GoogleOAuth2Response.java
  src/main/java/org/ezcode/codetest/application/usermanagement/user/dto/response/OAuth2Response.java
  src/main/java/org/ezcode/codetest/application/usermanagement/user/service/UserService.java
  src/main/java/org/ezcode/codetest/common/security/config/SecurityConfig.java
  src/main/java/org/ezcode/codetest/common/security/hander/CustomSuccessHandler.java
  src/main/java/org/ezcode/codetest/common/security/util/AESUtil.java
  src/main/java/org/ezcode/codetest/common/security/util/JwtFilter.java
  src/main/java/org/ezcode/codetest/common/security/util/SecurityPath.java
  src/main/java/org/ezcode/codetest/domain/user/exception/code/AuthExceptionCode.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/CustomOAuth2User.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/User.java
  src/main/java/org/ezcode/codetest/domain/user/model/entity/UserFactory.java
  src/main/java/org/ezcode/codetest/domain/user/repository/UserRepository.java
  src/main/java/org/ezcode/codetest/domain/user/service/CustomOAuth2UserService.java
  src/main/java/org/ezcode/codetest/domain/user/service/UserDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/user/UserRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/usermanagement/OAuth2Controller.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#107 refactor : category 리팩토링
  src/main/java/org/ezcode/codetest/application/problem/dto/request/ProblemCreateRequest.java
  src/main/java/org/ezcode/codetest/application/problem/dto/request/ProblemUpdateRequest.java
  src/main/java/org/ezcode/codetest/application/problem/dto/response/ProblemDetailResponse.java
  src/main/java/org/ezcode/codetest/application/problem/dto/response/ProblemResponse.java
  src/main/java/org/ezcode/codetest/application/problem/dto/response/ProblemSearchResponse.java
  src/main/java/org/ezcode/codetest/application/problem/service/ProblemSearchService.java
  src/main/java/org/ezcode/codetest/application/problem/service/ProblemService.java
  src/main/java/org/ezcode/codetest/domain/game/service/CharacterStatusDomainService.java
  src/main/java/org/ezcode/codetest/domain/problem/model/entity/Problem.java
  src/main/java/org/ezcode/codetest/domain/problem/model/entity/ProblemSearchDocument.java
  src/main/java/org/ezcode/codetest/domain/problem/model/enums/Difficulty.java
  src/main/java/org/ezcode/codetest/domain/submission/model/SubmissionResult.java
  src/main/java/org/ezcode/codetest/domain/submission/model/entity/UserProblemResult.java
  src/main/java/org/ezcode/codetest/infrastructure/elasticsearch/repository/ProblemElasticsearchAdapter.java
  src/main/java/org/ezcode/codetest/infrastructure/event/dto/GameLevelUpEvent.java
  src/main/java/org/ezcode/codetest/infrastructure/event/publisher/ProblemEventPublisher.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemQueryRepositoryImpl.java
  src/main/java/org/ezcode/codetest/presentation/game/play/TestGamePlayController.java
  src/main/resources/elasticsearch/my_index-settings.json
Labels: documentation

#112 refactor : 문제 카테고리 read 시 캐쉬 설정
  src/main/java/org/ezcode/codetest/application/submission/model/SubmissionContext.java
  src/main/java/org/ezcode/codetest/domain/game/model/character/CharacterRealStat.java
  src/main/java/org/ezcode/codetest/domain/problem/model/ProblemInfo.java
  src/main/java/org/ezcode/codetest/domain/problem/model/entity/Problem.java
  src/main/java/org/ezcode/codetest/domain/problem/model/entity/ProblemCategory.java
  src/main/java/org/ezcode/codetest/domain/problem/service/ProblemDomainService.java
  src/main/java/org/ezcode/codetest/infrastructure/cache/config/CaffeineCacheConfig.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemCategoryRepositoryImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/persistence/repository/problem/ProblemJpaRepository.java
Labels: enhancement

#114 refactor : 파일 2개 커밋 하나로 병합하는 로직 구현 (99.7%)
  src/main/java/org/ezcode/codetest/application/submission/dto/event/GitPushStatusEvent.java
  src/main/java/org/ezcode/codetest/application/submission/dto/request/github/GitHubPushRequest.java
  src/main/java/org/ezcode/codetest/application/submission/model/SubmissionContext.java
  src/main/java/org/ezcode/codetest/application/submission/port/SubmissionEventService.java
  src/main/java/org/ezcode/codetest/application/submission/service/GitHubPushService.java
  src/main/java/org/ezcode/codetest/application/submission/service/GitHubService.java
  src/main/java/org/ezcode/codetest/application/submission/service/SubmissionService.java
  src/main/java/org/ezcode/codetest/domain/submission/exception/GitHubClientException.java
  src/main/java/org/ezcode/codetest/domain/submission/exception/code/GitHubExceptionCode.java
  src/main/java/org/ezcode/codetest/infrastructure/event/dto/submission/response/GitPushStatusResponse.java
  src/main/java/org/ezcode/codetest/infrastructure/event/listener/RedisJudgeQueueConsumer.java
  src/main/java/org/ezcode/codetest/infrastructure/event/listener/SubmissionEventListener.java
  src/main/java/org/ezcode/codetest/infrastructure/event/publisher/StompMessageService.java
  src/main/java/org/ezcode/codetest/infrastructure/event/publisher/SubmissionEventPublisher.java
  src/main/java/org/ezcode/codetest/infrastructure/github/GitBlobCalculator.java
  src/main/java/org/ezcode/codetest/infrastructure/github/GitHubApiClient.java
  src/main/java/org/ezcode/codetest/infrastructure/github/GitHubClientImpl.java
  src/main/java/org/ezcode/codetest/infrastructure/github/GitHubContentBuilder.java
  src/main/java/org/ezcode/codetest/infrastructure/github/model/CommitContext.java
  src/main/java/org/ezcode/codetest/infrastructure/github/model/Extensions.java
  src/main/java/org/ezcode/codetest/infrastructure/github/model/FileType.java
  src/main/java/org/ezcode/codetest/infrastructure/github/model/PushStatus.java
  src/main/java/org/ezcode/codetest/presentation/submission/SubmissionController.java
  src/main/resources/application.properties
Labels: enhancement

#117 test(submission): add domain layer tests
  src/test/java/org/ezcode/codetest/domain/language/LanguageDomainServiceTest.java
  src/test/java/org/ezcode/codetest/domain/submission/SubmissionDomainServiceTest.java
Labels: Test

#120 test(submission): add infra layer tests
  build.gradle
  src/main/java/org/ezcode/codetest/infrastructure/judge0/Judge0Client.java
  src/test/java/org/ezcode/codetest/infrastructure/event/RedisJudgeQueueConsumerTest.java
  src/test/java/org/ezcode/codetest/infrastructure/event/RedisJudgeQueueProducerTest.java
  src/test/java/org/ezcode/codetest/infrastructure/github/GitHubClientTest.java
  src/test/java/org/ezcode/codetest/infrastructure/judge0/Judge0ClientTest.java
Labels: Test
